export default {
    loginPage: {
        usernameInput: '[data-test="username"]',
        passwordInput: '[data-test="password"]',
        loginButton: '[data-test="login-button"]',
        errorMessage: '[data-test="error"]',
    },
    itemsPage: {
        sortButton: '[data-test="product_sort_container"]',
        items: '.inventory_item',
        itemNames: '.inventory_item_name',
        itemPrices: '.inventory_item_price',
        itemDescriptions: '.inventory_item_description',
        itemImages: '.inventory_item_img',
        cartBadge: '.shopping_cart_badge',
        addToCart: '*[data-test^="add-to-cart"]',
    },
    detailsPage: {
        itemName: '.inventory_details_name',
        itemDescription: '.inventory_details_desc',
        itemImage: '.inventory_details_img',
        itemPrice: '.inventory_details_price',
        backToProductsButton: '[data-test="back-to-products"]',
        addToCart: '*[data-test^="add-to-cart"]',
    },
    cartPage: {
        itemQuantity: '.cart_quantity',
        itemName: '.inventory_item_name',
        itemDescription: '.inventory_item_desc',
        itemPrice: '.inventory_item_price',
        removeButton: '*[data-test^="remove-"]',
        continueShoppingButton: '[data-test="continue-shopping"]',
        checkoutButton: '[data-test="checkout"]',
    },
    checkoutStepOnePage: {
        firstName: '[data-test="firstName"]',
        lastName: '[data-test="lastName"]',
        postalCode: '[data-test="postalCode"]',
        errorMessage: '[data-test="error"]',
        continueButton: '[data-test="continue"]',
        cancelButton: '[data-test="cancel"]',
    },
    checkoutStepTwoPage: {
        itemTotal: '.summary_subtotal_label',
        tax: '.summary_tax_label',
        total: '.summary_total_label',
        finishButton: '[data-test="finish"]',
        cancelButton: '[data-test="cancel"]',
        summeryInfoLabel: '.summary_info_label',
        summeryValueLabel: '.summary_value_label',
        itemNames: '.inventory_item_name',
        itemDescriptions: '.inventory_item_desc',
        itemPrices: '.inventory_item_price',
        itemQuantities: '.cart_quantity',
    },
    completeCheckoutPage: {
        header: '.complete-header',
        text: '.complete-text',
        backHomeButton: '[data-test="back-to-products"]',
        image: '.pony_express',
    },
    burgerMenu: {
        openButton: '#react-burger-menu-btn',
        allItemsButton: '#inventory_sidebar_link',
        aboutButton: '#about_sidebar_link',
        logoutButton: '#about_sidebar_link',
        resetAppStateButton: '#about_sidebar_link',
        closeButton: 'react-burger-cross-btn',
    },
};
